apiVersion: "v1"
kind: "LimitRange"
metadata:
    name: "limits"
spec:
  limits:
    -
      type: "Pod"
      max:
        cpu: "1"
        memory: "128Mi"
      min:
        cpu: "10m"
        memory: "16Mi"
    -
      type: "Container"
      max:
        cpu: "1"
        memory: "128Mi"
      min:
        cpu: "100m"
        memory: "4Mi"
      default:
        cpu: "300m"
        memory: "200Mi"
      defaultRequest:
        cpu: "200m"
        memory: "100Mi"
      maxLimitRequestRatio:
        cpu: "10"
